feat(commands): add leaderboard command
backmeupplz/memcoin pull request #1
Opened 2018-08-11 23:27 UTC by MixailE

add command for info about balance top 10 users

2018-08-11 23:27 UTC, MixailE commented
merge feat(commands): add leaderboard command

2018-08-11 23:38 UTC, backmeupplz requested changes
Please, make sure you use `Leaderboard` instead of `LeaderBoard`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +import { User } from '../models/user';
Need to remove `;`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +interface UserForLeaderBoard {
Better to rename to `LeaderBoardUser`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +        username: getName(member),
Please, keep indentation to 2 spaces

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    balance: Number,
Better to use `number`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    username: String,
Better to use `string`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +const getUser = async (ctx: any, user: User): Promise<UserForLeaderBoard> => {
1. Remove return time (it will be inferred)
2. `ctx` should be `ContextMessageUpdate`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +const getUser = async (ctx: any, user: User): Promise<UserForLeaderBoard> => {
Functions should be declared as `function`, not as `const`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    const countUserInLeader = 10;
No need for extra variable, please just hardcode it to `countUserInLeader`

2018-08-11 23:38 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    // Get leaderboard users
Please, change to `// Get users leaderboard`

2018-08-11 23:38 UTC, backmeupplz commented on src/models/user.ts
> +export function getLeaderBalance(chatId: number, limit: number) {
Please, rename to `getLeaderboard`

2018-08-11 23:38 UTC, backmeupplz commented on src/models/user.ts
> +  return UserModel.find().sort({ balance: 'desc' }).limit(limit).exec();
Should be no need to use `exec` in the end

2018-08-12 00:11 UTC, backmeupplz requested changes

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +async function getUser(ctx: any, user: User): Promise<LeaderBoardUser> {
Please, remove return type

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +  }
Add `as LeaderBoardUser`

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +interface LeaderBoardUser {
Rename to `LeaderboardUser`

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +async function getUser(ctx: any, user: User): Promise<LeaderBoardUser> {
`ctx` argument should be of `ContextMessageUpdate` type

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    const text = `🏆  Топ Мемолиархов 🏆\n\n${list}`
Remove extra space after first `🏆`

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    const members = await Promise.all(users.map((user: User) => getUser(ctx, user)))
`members` should have a distinct type here. Add `: LeaderboardUser[]` here.

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    const list = members.map((member: LeaderBoardUser) => `*${member.string}*: *${member.number}*`).join('\n')
Remove casting a type (`: LeaderBoardUser`) from here — it should be inferred from the `members` type

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    string: getName(member),
Rename to `name`

2018-08-12 00:11 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    number: user.balance,
Rename to `balance`

2018-08-12 01:00 UTC, backmeupplz requested changes

2018-08-12 01:00 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +export function setupLeaderBoard(bot: Telegraf<ContextMessageUpdate>) {
Rename to `setupLeaderboard`

2018-08-12 01:00 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +  return ({
Remove `()`

2018-08-12 01:00 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +  bot.command('leaderboard', async (ctx: ContextMessageUpdate) => {
Remove `:ContextMessageUpdate`, it's inferred

2018-08-12 01:00 UTC, backmeupplz commented on src/commands/leaderboard.ts
> +    const members: LeaderboardUser[] = await Promise.all(users.map((user: User) => getUser(ctx, user)))
Remove `: User`, it's inferred

2018-08-12 01:00 UTC, backmeupplz commented on src/models/user.ts
> +export function getLeaderboard() {
Add `async`

2018-08-12 01:23 UTC, merged